### ISSUE TITLE
Texto "about" possivelmente incorreto

### ISSUE THREAD

**Issue by diegosurita** [raulfdm/personal-website#37]
Eai Raul Blz?

Vi um post seu no Medium e tomei a liberdade de fuçar um pouco no seu Github hehehe.

Quando acessei o seu site, lendo a sessão "About" acho que identifiquei um possível erro em um trecho do texto. Segue abaixo.
`I had no idea what could I do with technology and what it could offer to me, than just I give up.`

O texto correto não seria este?
`I had no idea what I could do with technology and what it could offer to me, then just I gave up.`

See ya!

**Comment by raulfdm** [comment]
Fala @diegosurita , tudo certo?

Osh cara.. se fosse só esse erro, tava ótimo! hahahah 🤣 

Peguei pra analisar o meu texto, achei vários erros e falta de concordância! Faz meses que não mexo nesse site! Obrigado pelo toque, vou corrigir isso!

**Comment by raulfdm** [comment]
Fixed
